CREATE TABLE `data_platform_process_order_header_data`        
(
		`ProcessOrder`                            int(16) NOT NULL,
		`ProductionPlantBusinessPartner`          int(12) NOT NULL,
		`ProductionPlant`                         varchar(4) DEFAULT NULL,
    	`ProcessOrderType`                        varchar(4) DEFAULT NULL,
    	`ProcessOrderIsReleased`                  tinyint(1) DEFAULT NULL,
    	`ProcessOrderIsConfirmed`                 tinyint(1) DEFAULT NULL,
    	`ProcessOrderIsPartiallyConfirmed`        tinyint(1) DEFAULT NULL,
		`CreationDate`                            date NOT NULL,
		`LastChangeDate`                          date NOT NULL,
    	`ProcessOrderIsLocked`                    tinyint(1) DEFAULT NULL,
    	`ProcessOrderIsClosed`                    tinyint(1) DEFAULT NULL,
    	`ProcessOrderHasGeneratedOperations`      tinyint(1) DEFAULT NULL,
    	`ProductAvailyIsNotChecked`               tinyint(1) DEFAULT NULL,
    	`Product`                                 varchar(40) DEFAULT NULL,
		`StorageLocation`                         varchar(4) DEFAULT NULL,
--		`GoodsRecipientName`                      varchar(100) DEFAULT NULL,
        `OrderInternalBillOfOperations`           int(3) DEFAULT NULL,
		`MRPArea`                                 varchar(10) DEFAULT NULL,
        `MRPController`                           varchar(3) DEFAULT NULL,
        `ProductionSupervisor`                    varchar(100) DEFAULT NULL,
        `ProductionVersion`                       varchar(4) DEFAULT NULL,
        `PlannedOrder`                            int(16) DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`ProcessOrderPlannedStartDate`            date DEFAULT NULL,
		`ProcessOrderPlannedStartTime`            time DEFAULT NULL,
		`ProcessOrderPlannedEndDate`              date DEFAULT NULL,
		`ProcessOrderPlannedEndTime`              time DEFAULT NULL,
		`ProcessOrderActualReleaseDate`           date DEFAULT NULL,
		`ProductionUnit`                          varchar(3) DEFAULT NULL,
        `TotalQuantity`                           float(15) DEFAULT NULL,
        `ProcessOrderPlannedScrapQty`             float(15) DEFAULT NULL,
        `ProcessOrderConfirmedYieldQty`           float(15) DEFAULT NULL,
        `HeaderText`                              varchar(200) DEFAULT NULL,
        `IsCancelled`                             tinyint(1) DEFAULT NULL,
        `IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,
       
    PRIMARY KEY (`ProcessOrder`, `ProductionPlantBusinessPartner`, `ProductionPlant`),
	
    CONSTRAINT `DataPlatformProcessOrderHeaderDataProductionPlantBusinessPartner_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`) REFERENCES `data_platform_bussiness_partnar_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataProductionPlant_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `Plant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProcessOrderHeaderDataProductionUnit_fk` FOREIGN KEY (`ProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
