CREATE TABLE `data_platform_process_order_sql_master_recipe_product_assignment_data`
(
		`ProductionPlantBusinessPartner`          int(12) NOT NULL,
        `ProcessOrder`                            int(16) NOT NULL,
        `ProcessOrderSequence`                    varchar(4) NOT NULL,
		`ProcessOrderOperation`                   varchar(4) NOT NULL,
		`OrderInternalBillOfOperations`           varchar(4) NOT NULL,
		`RecipeProduct`                           varchar(40) DEFAULT NULL,
		`ProducrionPlant`                         varchar(4) DEFAULT NULL,
        `ProcessOrderType`                        varchar(4) DEFAULT NULL,
        `MasterRecipeGroup`                       int(8) DEFAULT NULL,
        `MasterRecipe`                            int(4) DEFAULT NULL,
        `PlannedOrder`                            int(16) DEFAULT NULL,             
		`OrderID`                                 int(16) DEFAULT NULL,        
    	`OrderItem`                               int(6) DEFAULT NULL,
        `BillOfMaterial`                          int(16) DEFAULT NULL,               
    	`BOMItem`                                 int(6) DEFAULT NULL,        
        `StorageLocation`                         varchar(4) DEFAULT NULL,                
		`Batch`                                   varchar(10) DEFAULT NULL,     
		`ProductCompIsAlternativeItem`            tinyint(1) DEFAULT NULL,
	    `ComponentScrapInPercent`                 float(6) DEFAULT NULL,
        `OperationScrapInPercent`                 float(6) DEFAULT NULL,
		`BaseUnit`                                varchar(3) DEFAULT NULL,
		`RequiredQuantity`                        float(15) DEFAULT NULL,                 
        `WithdrawnQuantity`                       float(15) DEFAULT NULL,                  
        `ConfirmedAvailableQuantity`              float(15) DEFAULT NULL,                           
        `ProductCompOriginalQuantity`             float(15) DEFAULT NULL,                            
        `CreationDate`                            date DEFAULT NULL,             
        `LastChangeDate`                          date DEFAULT NULL,               
        `ValidityStartDate`                       date DEFAULT NULL,                  
        `ValidityEndDate`                         date DEFAULT NULL,                
        `IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,                    

    PRIMARY KEY (`ProductionPlantBusinessPartner`, `ProcessOrder`, `ProcessOrderSequence`, `ProcessOrderOperation`, `OrderInternalBillOfOperations`),
	
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentData_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProcessOrder`) REFERENCES `data_platform_process_order_header_data` (`BusinessPartner`, `ProcessOrder`),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataProductionStorageLocation_fk` FOREIGN KEY (`ProductionPlant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataMasterRecipe_fk` FOREIGN KEY (`MasterRecipe`) REFERENCES `data_platform_master_recipe_header_data` (`MasterRecipe`),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataBillOfMaterialItem_fk` FOREIGN KEY (`BillOfMaterial`, `BOMItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BOMItem`,),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataProductionOrders_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProcessOrderMasterRecipeProductAssignmentDataProductionBatch_fk` FOREIGN KEY (`Batch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Batch`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
